---
name: Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        shell: [pwsh]
        include:
          - os: windows-latest
            shell: powershell
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
